### ISSUE TITLE
Help with updating CONTRIBUTING.md

### ISSUE THREAD

**Issue by RobSullivan** [RobSullivan/pmc-ref#15]
This page is new and needs updating.

**Comment by RobSullivan** [comment]
I'm not very good at markdown and can't figure out how to make the table of contents link down to the appropriate header, would appreciate some help :smile:

**Comment by KirstieJane** [comment]
I think I can figure that out.... stay tuned for a pull request soon :smile:

**Comment by RobSullivan** [comment]
Pull request #16 closes this issue. Thanks for your help.
