### ISSUE TITLE
Fix config and or set up env variables so can run locally without Heroku Toolbelt if want to.

### ISSUE THREAD

**Issue by RobSullivan** [RobSullivan/pmc-ref#38]
The up and running section is confusing and it's a faff to start the application.

https://github.com/RobSullivan/pmc-ref/blob/master/CONTRIBUTING.md#up-and-running

Make it as simple as possible to start the application with or without Heroku.

**Comment by acabunoc** [comment]
This should help with this! https://github.com/RobSullivan/pmc-ref/pull/66

**Comment by RobSullivan** [comment]
Closed by #66
