### ISSUE TITLE
Run as a client-side application

### ISSUE THREAD

**Issue by hubgit** [RobSullivan/pmc-ref#6]
I think this sequence of EUtils queries will generate the same information, so it might be easier to make the requests in the browser?:

Get the PMID for a DOI:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=10.1371/journal.pgen.1004432[DOI]

Get cited PMIDs:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?linkname=pubmed_pubmed_refs&id=24901476

Get cited PMC IDs:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?linkname=pubmed_pmc_refs&id=24901476
or
http://www.ncbi.nlm.nih.gov/pmc/?linkname=pubmed_pmc_refs&from_uid=24901476

**Comment by hubgit** [comment]
If the full-text XML is in PMC, then this will fetch the full XML for counting the total number of references:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=4046971

**Comment by hubgit** [comment]
I realised that this tool makes most sense as a server-side API, so closing this.

**Comment by RobSullivan** [comment]
Thanks for sharing those eutils links, they're useful as pmc-ref doesn't retrieve full XML for count the total number of references. Will keep it in mind.
