### ISSUE TITLE
Get status 'doi not found' for all of the DOIs I've tried.

### ISSUE THREAD

**Issue by alexmorley** [RobSullivan/pmc-ref#73]
Using: Mozilla Firefox 42.0
On: Linux, Fedora 21

E.g: 10.1073/pnas.0811054106 --> {"article":[]} OR {"result":"doi not found"}

They work on https://www.doi.org/ ...

am I doing something wrong??

**Comment by RobSullivan** [comment]
Hi Alex, 

No you're not doing anything wrong at all! 

I may not have data for that doi yet, I will check as soon as possible and let know. 

Thanks for trying it out.

**Comment by RobSullivan** [comment]
Yep, I don't have the data for 10.1073/pnas.0811054106 at this stage. 

I have some work to do to look up dois that I don't have on the fly so until then I've opened #76 to clarify things.
