### ISSUE TITLE
Update the About page

### ISSUE THREAD

**Issue by RobSullivan** [RobSullivan/pmc-ref#76]
**The problem**

The [About](http://pmc-ref.herokuapp.com/about) page is misleading as it gives the impression that _all_ PubMed data is available for checking. It's not! There's only data for ~70,000 (or 120k - need to check but err on the side of caution eh?) articles.

**What is needed**

The [About](https://github.com/RobSullivan/pmc-ref/blob/master/views/about.html) page should clarify how much data is available but mention a project to make it dynamic is underway :smile: (see https://github.com/RobSullivan/pmc-cite-ref ). 

**Steps to fix**

 - [x] Claim this issue (by @Deborah-Digges )

Either 
 - [ ] Fork this repository - as it's a change to HTML the application doesn't need to be set up locally but the file can be changed in GitHub

Or

 - [ ] [Setup repository locally](https://github.com/RobSullivan/pmc-ref/blob/master/CONTRIBUTING.md#getting-started) and get the tests running

Then

 - [x] Edit the html to include clarification that a small corpus of data is available for checking

- [x] Submit a Pull Request! If working on your first Pull Request a good resource is [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) (Thanks [Hoodie team](https://github.com/hoodiehq) for resource).

-  [x] Me to review!

**Comment by Deborah-Digges** [comment]
I'd like to help with this, please.

**Comment by Deborah-Digges** [comment]
@RobSullivan please do review this PR: https://github.com/RobSullivan/pmc-ref/issues/91

**Comment by RobSullivan** [comment]
Thanks again, @Deborah-Digges, have merged #91
